### ISSUE TITLE
Cannot build package

### ISSUE THREAD

**Issue by szop85** [brutasse/graphite-api#126]
Hey guys,

first of all: Thank you for your effort working on this code :). I'm getting always following error:

```
root@server631:/tmp/graphite-api-1.0.2-rc1/fpm# ./build-deb.sh
+ export VERSION=1.0.1
+ VERSION=1.0.1
+ mkdir -p build/usr/share/python
+ virtualenv build/usr/share/python/graphite
New python executable in build/usr/share/python/graphite/bin/python
Installing setuptools, pip...done.
+ build/usr/share/python/graphite/bin/pip install -U pip distribute
Traceback (most recent call last):
  File "build/usr/share/python/graphite/bin/pip", line 7, in <module>
    from pip import main
  File "/tmp/graphite-api-1.0.2-rc1/fpm/build/usr/share/python/graphite/local/lib/python2.7/site-packages/pip/__init__.py", line 11, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/tmp/graphite-api-1.0.2-rc1/fpm/build/usr/share/python/graphite/local/lib/python2.7/site-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/tmp/graphite-api-1.0.2-rc1/fpm/build/usr/share/python/graphite/local/lib/python2.7/site-packages/pip/download.py", line 22, in <module>
    from pip._vendor import requests, six
  File "/tmp/graphite-api-1.0.2-rc1/fpm/build/usr/share/python/graphite/local/lib/python2.7/site-packages/pip/_vendor/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/tmp/graphite-api-1.0.2-rc1/fpm/build/usr/share/python/graphite/local/lib/python2.7/site-packages/pip/_vendor/requests/utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/tmp/graphite-api-1.0.2-rc1/fpm/build/usr/share/python/graphite/local/lib/python2.7/site-packages/pip/_vendor/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/tmp/graphite-api-1.0.2-rc1/fpm/build/usr/share/python/graphite/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/tmp/graphite-api-1.0.2-rc1/fpm/build/usr/share/python/graphite/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/__init__.py", line 16, in <module>
    from .connectionpool import (
  File "/tmp/graphite-api-1.0.2-rc1/fpm/build/usr/share/python/graphite/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 33, in <module>
    from .connection import (
  File "/tmp/graphite-api-1.0.2-rc1/fpm/build/usr/share/python/graphite/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 41, in <module>
    from .util import (
  File "/tmp/graphite-api-1.0.2-rc1/fpm/build/usr/share/python/graphite/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/__init__.py", line 5, in <module>
    from .ssl_ import (
  File "/tmp/graphite-api-1.0.2-rc1/fpm/build/usr/share/python/graphite/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 4, in <module>
    from ..exceptions import SSLError, InsecurePlatformWarning
ImportError: cannot import name InsecurePlatformWarning
```

```
root@server631:/tmp/graphite-api-1.0.2-rc1/fpm# python -V
Python 2.7.6
```

I'm working on Ubuntu 14.04 LTS. Any idea what this means and how to fix it?

Cheers,
Szop

**Comment by brutasse** [comment]
Is it a fresh Ubuntu install? What version of virtualenv do you have?

**Comment by szop85** [comment]
Hey,

it's:

```
root@server631:/# apt-cache policy python-virtualenv
python-virtualenv:
  Installed: 1.11.4-1
  Candidate: 1.11.4-1
  Version table:
 *** 1.11.4-1 0
        500 http://mirror.syseleven.de/ubuntu-trusty/ trusty/universe amd64 Packages
        100 /var/lib/dpkg/status
```

Cheers,
Szop

**Comment by brutasse** [comment]
I'm not sure about the root cause of the issue but if I `rm -rf build/` before every attempt, the script runs without any problem. Can you try that?

**Comment by szop85** [comment]
Hey @brutasse. Works like a charm :)

Cheers,
Szop

**Comment by brutasse** [comment]
Thanks for confirming, I just added it to the build script :)
