### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'step'

### ISSUE THREAD

**Issue by Dieterbe** [brutasse/graphite-api#85]
upon requesting `target=movingAverage(stats.*.deploy.*.clearapc.duration.sum,10)` I get:
```
{"exception": "AttributeError(\"'NoneType' object has no attribute 'step'\",)", "event": "Exception"}
{"event": "Traceback (most recent call last):\n"}
{"event": "  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1817, in wsgi_app\n    response = self.full_dispatch_request()\n"}
{"event": "  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1477, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n"}
{"event": "  File \"/usr/local/lib/python2.7/dist-packages/newrelic-2.40.0.34/newrelic/hooks/framework_flask.py\", line 86, in _nr_wrapper_Flask_handle_exception_\n    return wrapped(*args, **kwargs)\n"}
{"event": "  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1381, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n"}
{"event": "  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1475, in full_dispatch_request\n    rv = self.dispatch_request()\n"}
{"event": "  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1461, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n"}
{"event": "  File \"/usr/local/lib/python2.7/dist-packages/newrelic-2.40.0.34/newrelic/hooks/framework_flask.py\", line 30, in _nr_wrapper_handler_\n    return wrapped(*args, **kwargs)\n"}
{"event": "  File \"/usr/local/lib/python2.7/dist-packages/graphite_api/app.py\", line 394, in render\n    series_list = evaluateTarget(context, target)\n"}
{"event": "  File \"/usr/local/lib/python2.7/dist-packages/graphite_api/app.py\", line 470, in evaluateTarget\n    result = evaluateTokens(requestContext, tokens)\n"}
{"event": "  File \"/usr/local/lib/python2.7/dist-packages/graphite_api/app.py\", line 480, in evaluateTokens\n    return evaluateTokens(requestContext, tokens.expression)\n"}
{"event": "  File \"/usr/local/lib/python2.7/dist-packages/graphite_api/app.py\", line 492, in evaluateTokens\n    return func(requestContext, *args, **kwargs)\n"}
{"event": "  File \"/usr/local/lib/python2.7/dist-packages/graphite_api/functions.py\", line 867, in movingAverage\n    seconds=bootstrapSeconds)\n"}
{"event": "  File \"/usr/local/lib/python2.7/dist-packages/graphite_api/functions.py\", line 2024, in _fetchWithBootstrap\n    if bootstrap.step != original.step:\n"}
{"event": "AttributeError: 'NoneType' object has no attribute 'step'\n"}
```

requesting `target=stats.*.deploy.*.clearapc.duration.sum` works fine
i can provide more data if you want (tell me where to add logger calls or whatever and i'll run it)

**Comment by zyegfryed** [comment]
Got the same error since I updated to v1.1. Can give some more info upon request.

**Comment by brutasse** [comment]
@zyegfryed 1.1 returns the full traceback in the HTTP response, can you share it?

**Comment by zyegfryed** [comment]
@brutasse sure, here it is:
```
Stacktrace (most recent call last):
  File "flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "graphite_api/app.py", line 401, in render
    series_list = evaluateTarget(context, target, data_store)
  File "graphite_api/app.py", line 496, in evaluateTarget
    result = evaluateTokens(requestContext, tokens, data_store)
  File "graphite_api/app.py", line 506, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, data_store)
  File "graphite_api/app.py", line 514, in evaluateTokens
    arg, data_store) for arg in tokens.call.args]
  File "graphite_api/app.py", line 506, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression, data_store)
  File "graphite_api/app.py", line 520, in evaluateTokens
    ret = func(requestContext, *args, **kwargs)
  File "graphite_api/functions.py", line 729, in movingMedian
    seconds=bootstrapSeconds)
  File "graphite_api/functions.py", line 2091, in _fetchWithBootstrap
    if bootstrap.step != original.step:
```

**Comment by zyegfryed** [comment]
Here's some context about the error:
<img width="1280" alt="screen shot 2015-10-12 at 18 42 28" src="https://cloud.githubusercontent.com/assets/185375/10433302/0955c068-7111-11e5-8eed-7c5e7b21a1ad.png">
FYI when I expand the context for both `b` and `bootstrap`, all the 49 values are `None`.

**Comment by brutasse** [comment]
@zyegfryed can you try with the commit I added a couple of days ago? Are you using carbon/whisper or something else?

**Comment by zyegfryed** [comment]
@brutasse yes, I'm gonna try it today and let you know. I'm using carbon/whisper with [statsite](https://github.com/armon/statsite) in front.

**Comment by brutasse** [comment]
Ok -- I still see the issue in some cases with whisper, which is why I didn't close the issue with my commit. But it happens less often now.

**Comment by zyegfryed** [comment]
Not better for me I'm afraid  :(
I keep getting the error raised, everytime...

<img width="1280" alt="screen shot 2015-10-20 at 12 01 25" src="https://cloud.githubusercontent.com/assets/185375/10604077/55618a7a-7722-11e5-8fa9-a6b3d0bdac1d.png">
<img width="1280" alt="screen shot 2015-10-20 at 11 59 14" src="https://cloud.githubusercontent.com/assets/185375/10604063/42effcdc-7722-11e5-94e6-587e52485a01.png">

**Comment by crazed** [comment]
I also am encountering this issue with the latest version master. Same stack trace as well.

**Comment by zyegfryed** [comment]
@brutasse I can confirm it resolved the issue for me. Thanks a lot!

**Comment by brutasse** [comment]
@zyegfryed great, thanks for confirming :)
